# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres:14.8
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432